[aliases]
# https://shaddy.dev/notes/jj-tug/
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[ui]
pager = "less -FRX"
diff-formatter = "delta"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
# Shorter IDs for prompts and compact displays
'format_short_change_id(id)' = 'id.shortest(4)'
'format_short_commit_id(id)' = 'id.shortest(4)'

[revset-aliases]
# Find the closest bookmark ancestor - useful for prompts showing distance from bookmark
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
